### ISSUE TITLE
When sorting IAM User's Access Key Age column, sort alphabetically, not numeric.

### ISSUE THREAD

**Issue by jihyungSong** [cloudforet-io/plugin-aws-cloud-service-inven-collector#18]
In the case of IAM User's Access Key Age, when column sorting is performed, alphabetical rather than numeric is sorted.
Because it is a string value of "xx days".

<img width="596" alt="image" src="https://user-images.githubusercontent.com/7124443/201645909-23bdf046-0406-48c2-bf0b-02e75b252feb.png">

**Comment by jihyungSong** [comment]
For sorting, modify column data be stored in integer format, and use `postfix` as `options` value.

```yaml
  - key: data.access_key_age
    name: Access Key Age
    options:
      postfix: ' days'
    type: text
  - key: data.last_active_age
    name: Last Activity
    options:
      postfix: ' days'
    type: text
```

However, it does not complete because this `postfix` feature of the specification has not yet been developed in the Console. 
This issue will be closed after applying the `postfix` feature in console.
